### ISSUE TITLE
ELK stack chart

### ISSUE THREAD

**Issue by Klazomenai** [clearmatics/charts-ose#124]
As a user
I want an ELK stack
So that I can look and analyse logs

### Description
The general consensus is that Stackdriver is not suitable for engineers

### Acceptance criteria
- [ ] Pods related to this stack must not run on the any of the Validator nodes
- [ ] Persistent storage
- [ ] Logs flow changed from Stackdriver to the new ELK stack
- [ ] Segregation by separate namespace
- [ ] Relevant Wikis for relevant deployments updated

Related issues: https://github.com/clearmatics/www-devops/issues/46

**Comment by eastata** [comment]
- Why logstash?
- Why we can't use helm charts that already exist in helm `stable`?
- Requirements to log producers must be defined. What kind of logs we have to collect? blocker: https://github.com/clearmatics/www-devops/issues/46
