### ISSUE TITLE
Archive this repo

### ISSUE THREAD

**Issue by Klazomenai** [clearmatics/charts-ose#184]
### User story
As a user,
I want this repository archived.

### Description
To simplify the Helm 3 migration, this original Helm 2 repository was maintained purely for Helm 2. This repository now needs tidying up in terms of issues, references need updating and it needs archiving to prevent future confusion.

### Acceptance criteria
- [x] Remaining issues to be migrated to the [charts-ose-helm3](url) repository
- [x] All internal documentation which references this repository are to be updated
- [ ] Repository archived via notification to: @aiman 

### Related issues
Note: This issue has not been fully groomed yet. This issue needs to be turned into an Epic and [all of the documentation which reference this Helm charts repo](https://github.com/search?p=4&q=org%3Aclearmatics+charts-ose&type=Code) need issues opened and referenced here.

**Comment by eastata** [comment]
issues was migrated to the charts-ose-helm3 repository

**Comment by eastata** [comment]
>  All internal documentation which references this repository are to be updated

@Klazomenai could you provide list of documentation to be updated

**Comment by Klazomenai** [comment]
> @Klazomenai could you provide list of documentation to be updated

Anywhere where documentation links exist within repositories within the Clearmatics GitHub organisation.
